### ISSUE TITLE
Secure Deployment Configuration

### ISSUE THREAD

**Issue by dactylroot** [statueofmike/raspi-ml#1]
Document/script how to prepare a box for deployment.

1. disable login GUI
    - uninstall X utils?
2. disable ssh
    - SSH can be re-enabled later manually.
3. set up splash screens

**Comment by statueofmike** [comment]
Security during execution might be done through [xscreensaver](https://www.jwz.org/xscreensaver/man1.html).

**Comment by dactylroot** [comment]
implemented in subramgo/Signage/issues/7
